Repository plone/plone.app.contenttypes, pull requests merged in 2018-10, with the labels that each got.

#494 Fix folder layout property migration
  CHANGES.rst
  plone/app/contenttypes/migration/migration.py
Labels: 02 type: regression, 12 prio: high, 23 status: testing, 32 needs: review

#496 Revert the breaking lead image and richt text behavior change.
  CHANGES.rst
  plone/app/contenttypes/behaviors/configure.zcml
  plone/app/contenttypes/behaviors/leadimage.py
  plone/app/contenttypes/behaviors/richtext.py
  plone/app/contenttypes/profiles/default/types/Collection.xml
  plone/app/contenttypes/profiles/default/types/Document.xml
  plone/app/contenttypes/profiles/default/types/Event.xml
  plone/app/contenttypes/profiles/default/types/News_Item.xml
  plone/app/contenttypes/testing.py
  plone/app/contenttypes/tests/test_behaviors_leadimage.py
  plone/app/contenttypes/tests/test_behaviors_richtext.py
  plone/app/contenttypes/tests/test_collection.py
  plone/app/contenttypes/tests/test_document.py
  plone/app/contenttypes/tests/test_event.py
  plone/app/contenttypes/tests/test_link.py
  plone/app/contenttypes/tests/test_migration_custom.py
  plone/app/contenttypes/tests/test_migration_topic.py
  plone/app/contenttypes/tests/test_news_item.py
  plone/app/contenttypes/upgrades.py
Labels: 02 type: regression, 11 prio: blocker, 24 status: ready, 32 needs: review

#495 close files
  CHANGES.rst
  plone/app/contenttypes/tests/test_behaviors_leadimage.py
  plone/app/contenttypes/tests/test_collection.py
  plone/app/contenttypes/tests/test_file.py
  plone/app/contenttypes/tests/test_image.py
  plone/app/contenttypes/tests/test_indexes.py
Labels: 23 status: testing
